import delete_btn from '../assets/icons/delete.svg'
import edit from '../assets/icons/edit.png'

const order_data = {
    orders: [
        {order: 'order name', order_id: '18', sl_no: '1', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order Vivek', order_id: '18', sl_no: '2', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '3', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '4', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '5', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '6', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '09', sl_no: '7', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '8', seller: 'seller khannal', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '9', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn}, 
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '11', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '12', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '13', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '14', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '15', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '16', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '17', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '18', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '19', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '20', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '21', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '22', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '23', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '24', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '25', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '26', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '27', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '29', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '30', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '31', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '32', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '33', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '34', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '35', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '36', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '37', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '38', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '38', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '39', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '40', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '41', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '42', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '43', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '44', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '45', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '46', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '47', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '48', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '49', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '50', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'Hoobb Shaw', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
        {order: 'order name', order_id: '18', sl_no: '10', seller: 'seller name', remarks: 'remarks', edit: edit, delete: delete_btn},
    ],
};

export default order_data